Issue #354 - Rework table support
NASA-AMMOS/AIT-Core pull request #355
Opened 2021-08-04 23:12 UTC by MJJoyce

Rework Core table support to provide users with more consistent and
understandable feature set. Table encoding / decoding functionality has
been (hopefully) simplified via simpler, more flexible APIs, extraction
of hardcoded functionality, and leveraging of other Core functionality
such as dtype.py where possible.

Table encoding and decoding APIs have been cleaned up and made more
flexible so users can pass inputs in expected formats. Some
functionality has been extracted out of table.py into the encode /
decode CLI scripts (where it arguably belonged to begin with) in an
effort to keep Core functionality and abstractions cleaner. For example,
writing a decoded table to a file is no longer a requirement as part of
table decoding.

Column field handling now uses date type information for encoding /
decoding. This maintains consistency with the rest of the toolkit and
will allow easier extension of toolkit functionality when Extension
support is added to table.py.

Encode / decode CLI scripts have been rewritten. Their argument
structures have been simplified in the process.

The default table configuration formation and table.yaml file have been
simplified. A number of attributes have been removed from the dictionary
structures since they weren't supported by the toolkit anyway.

2021-08-04 23:15 UTC, MJJoyce commented
This is pending a few more changes before it's fully ready. At the very least I want to include documentation updates here. The current docs for table stuff is pretty spartan (read, crappy). I also want to add Extensions support to this but I might pull that work out into a separate ticket.

2021-08-05 21:26 UTC, MJJoyce commented
This should be good to merge now that the documentation is updated. I'm going to open a follow on ticket to address the `Extensions` support to table since it's not completely trivial (I think).

Note, the NASA AMMOS org seems to have used up its TravisCI credits so the build isn't running. Lovely. Proof that the branch is passing at the moment:

![Screen Shot 2021-08-05 at 14 25 18](https://user-images.githubusercontent.com/860902/128423264-f6c60d06-50b9-41fa-9622-5f90d2f6453a.png)

2021-08-16 21:58 UTC, nttoole requested changes
table.py has some copy/pasted comments that mention Command instead of the correct type

2021-08-16 23:00 UTC, nttoole commented
For ait_table_decode(), would there be any value in having results dumped to stdout if out_file is not provided?

2021-08-16 23:07 UTC, MJJoyce commented
Hey @nttoole,

Thanks for catching the Commanding stuff. I should have checked further when I stumbled across the mixups in the original code but forgot to follow up on it.

In terms of `ait_table_decode`, we certainly could. Happy to cover that in a follow up ticket. Most of the "real life" examples of these tables are pretty big but that's of course project specific.

2021-08-16 23:14 UTC, MJJoyce commented
@nttoole, searched through the docstrings and fixed the Command references. Should look better now.

2021-08-17 00:38 UTC, nttoole commented
@MJJoyce Looking at [test_table](https://github.com/NASA-AMMOS/AIT-Core/blob/issue-354/ait/core/test/test_table.py), is it correctly exercising the enum-type field?

2021-08-17 17:34 UTC, MJJoyce commented
> @MJJoyce Looking at [test_table](https://github.com/NASA-AMMOS/AIT-Core/blob/issue-354/ait/core/test/test_table.py), is it correctly exercising the enum-type field?

It is. That being said, I actually intended to remove the enumeration handling entirely (which I clearly failed to do) but I'm wondering if that's not the correct decision ...

Let me think on that a bit

2021-08-17 20:54 UTC, MJJoyce commented
@nttoole,
Updates pushed for enumeration handling. This is now properly handled on both encode and decode (with options to not include enumerates on decode). Tests have been added.

Heres an example run of stuff
```
(ait-core) > $ more test.txt
1, 2, 3
4, 5, 1
4, 5, TEST_ENUM_1

(ait-core) > $ ait/core/bin/ait_table_encode.py TestTable test.txt
[ ... ]
2021-08-17T13:39:19.835 | PROGRAM  | done.

(ait-core) > $ ait/core/bin/ait_table_decode.py test.bin
[ ... ]
2021-08-17T13:39:27.668 | PROGRAM  | done.

(ait-core) > $ more test_decoded.txt
# uptype=1
# HEADER_COLUMN_TWO=2
# HEADER_COLUMN_THREE=3
4,5,TEST_ENUM_1
4,5,TEST_ENUM_1
0,0,TEST_ENUM_0

(ait-core) > $ ait/core/bin/ait_table_decode.py --raw test.bin
[ ... ]
2021-08-17T13:42:47.273 | PROGRAM  | done.

(ait-core) > $ more test_decoded.txt
# uptype=1
# HEADER_COLUMN_TWO=2
# HEADER_COLUMN_THREE=3
4,5,1
4,5,1
0,0,0
```

Note in the enumerated case that fill values will get converted to their enumerated output. A potential reason that raw option might be useful ;)

2021-08-30 15:14 UTC, merged