#438 Add ability to route packets based on APID
NASA-AMMOS/AIT-Core pull request #439
Opened 2022-04-28 00:49 UTC by kmarwah

Implements a plugin which routes CCSDS packets by APID based on a table described in a .yaml file.

2022-05-04 23:24 UTC, nttoole requested changes
@kmarwah Could you please rename files from 'routing' to something more specific like 'apid_router'?  Thank you

2022-05-04 23:39 UTC, nttoole requested changes
Also, could you please document the arguments/return values/exceptions as part of the method docstrings?

2022-05-16 16:45 UTC, kmarwah commented
@nttoole done

2022-05-17 17:57 UTC, nttoole commented on doc/source/ait.core.server.plugins.routing.rst
> +ait.core.server.plugins.apid_routing module
@kmarwah Please update filename to reflect changes

2022-05-17 17:57 UTC, nttoole commented on doc/source/ait.core.server.plugins.rst
> +   ait.core.server.plugins.routing
@kmarwah Please update line to reflect changes

2022-05-17 18:39 UTC, kmarwah commented
Just updated the documentation file names

2022-05-17 18:44 UTC, nttoole approved these changes

2022-05-17 19:50 UTC, merged